# Basic arguments
work_dir: '/data/gpfs/projects/punim1598/data/work_dir/purls_12r'

# Processor
gpus: 1
num_epoch: 100

# Debug
seed: 5
eval_interval: 1

# Data
root: '/data/gpfs/projects/punim1598/data/ntu/zsl/synse_resources'
root2: '/data/gpfs/projects/punim1598/data/ntu/nturgbd_skel/zsl_splits'
dataset: 'shift_12_r' # Path to the generated visual features
dataloader: 'ntu_60'
split: 12
data_type: 'full'

# Model
model_name: 'purls'
lr: 1e-4
model_args:
  input_size: 256
  hidden_size :  512
  output_size: 100
  emb_dim :  512
  n_hidden_layers: 0

# Ablation
activate_train: True
test_p: False
resume: True
        
